### ISSUE TITLE
How to use install to hdd correctly?

### ISSUE THREAD

**Issue by b1t0y** [MuntashirAkon/Chrome-OS-Multiboot#1]
@MuntashirAkon in your github what do you mean 
 Install in HDD with cd ~/Downloads/ChromeOS/ && sudo bash install_chromium.sh chromiumos_image.img sda4 sda5 sda6.  Do I use exactly this command then replace after installing to HDD Or do I replace it right away while executing install_chromium.sh? Thanks

**Comment by MuntashirAkon** [comment]
I think you've got confused. The command (`cd ~/Downloads/ChromeOS/ && sudo bash install_chromium.sh chromiumos_image.img sda4 sda5 sda6`) is based on the assumption that you've placed all the required files inside `~/Downloads/ChromeOS` folder and the partition IDs are `sda4`, `sda5` and `sda6` for **EFI-SYSTEM**, **ROOT-A** and **STATE** partition respectively. You may have to change them based on how many partitions you have and how you assigned partition ID. So, by **replacing**, I meant that the arguments have to be replaced right away, ie. you don't have to run the exact command and then run the same command again by replacing the arguments.

**EDIT:** I've updated [Installing on HDD](https://github.com/MuntashirAkon/Chrome-OS-Multiboot/blob/master/README.MD#installing-on-hdd) to add more clarity.

**Comment by b1t0y** [comment]
@MuntashirAkon Thanks for the clarification and responding. So meaning if the hdd partition that i made shows sda7, sda8, sda9 (EFI-SYSTEM , ROOT-A and STATE) I will just change the sda4,5,6 on the script to sda7,8,9. Btw, do you use clover bootloader for multiboot windows, osx, linux and chrome os or you use a different bootloader? May I know your setup for multiboot and what oses? I really want to quad boot with just one hdd/ssd.  Thank you so much.

**Comment by MuntashirAkon** [comment]
> if the hdd partition that i made shows sda7, sda8, sda9 (EFI-SYSTEM , ROOT-A and STATE) I will just change the sda4,5,6 on the script to sda7,8,9.

Yes.

> do you use clover bootloader for multiboot windows, osx, linux and chrome os or you use a different bootloader?

I use Clover (EFI, not legacy).

> May I know your setup for multiboot and what oses?

It's a Dell Inspiron 15 5567 (7 gen) laptop. I've one SSD with macOS Mojave installed and another HDD (replaced with DVD Drive) where I've installed Windows 10 Pro, Ubuntu, Chrome OS, another macOS Mojave and macOS High Sierra. All of them are bootable via Clover.

That saying, the **install_chromium.sh** is modified the Chrome OS Grub bootloader in a way that you can directly boot into Chrome OS by selecting the Chrome OS menu in Clover.

**Comment by b1t0y** [comment]
Please help I tried the script and it says failed updating partition data, please try fixing it manually? What should i do?  Below is how i did the command.   Thanks

localhost /home/chronos/user/Downloads # sudo bash install_chromium.sh chromiumos_image.img sdc7 sdc8 sdc9
logname: no login name
ChromiumOS HDD installer
------------------------

Copying EFI-SYSTEM...Done.
Copying ROOT-A...Done.
Copying STATE...Done.
Fixing GRUB...Done.
Updating partition data...sed: -e expression #8, char 1: e/r/w commands disabled in sandbox mode

Failed updating partition data, please try fixing it manually.
Fixing touchpad...Done.
Installation complete!

**Comment by MuntashirAkon** [comment]
> sed: -e expression #8, char 1: e/r/w commands disabled in sandbox mode

Which operating system are you using to run this command? Chrome/Chromium OS? On VirtualBox/VMWare?

> Failed updating partition data, please try fixing it manually.

Mount **sdc8** and send me the file located `{/path/to/sdc8}/usr/sbin/write_gpt.sh`, I'll fix it for you.

**Comment by b1t0y** [comment]
> Which operating system are you using to run this command? Chrome/Chromium OS? On VirtualBox/VMWare?
I use chrome os shell/chronos.  Should I use linux like ubuntu instead? 

> Mount sdc8 and send me the file located 
Will send it in a while. Will try it in linux ubuntu first if it works. Thanks so much.

**Comment by MuntashirAkon** [comment]
> I use chrome os shell/chronos. Should I use linux like ubuntu instead?

If you've time, please download the latest install_chromium.sh and try it on Chrome OS. The issue should be fixed now.

**Comment by b1t0y** [comment]
1.If you've time, please download the latest install_chromium.sh and try it on Chrome OS. The issue should be fixed now.

I installed the old script with ubuntu and it worked!!! But I will try it with the new install_chromium.sh with chrome os and give you feedback.  One issue though, the first boot starts with "system is repairing" that counts down for about 5 mins. Then after reboot, it goes to the normal login and can use the chrome os without any issues. Is that normal? Thanks so much for making this! I can multiboot win10, osx mojave, ubuntu, prime os and chrome os in one ssd drive! :)

**Comment by MuntashirAkon** [comment]
> the first boot starts with "system is repairing" that counts down for about 5 mins.

It probably depends on how you made the **chromium_os.img**. “System is repairing” implies that it is performing a power wash (ie. recreate **STATE** partition).

**Comment by b1t0y** [comment]
> It probably depends on how you made the chromium_os.img. “System is repairing” implies that it is performing a power wash (ie. recreate STATE partition).

I used croissant.sh instead of chromefy.sh and fydeos6.0.img with samus73.bin recovery and swtpm.tar to have chrome:flags enabled in chrome. Coz when i use eve and caroline recovery chrome:flags on chrome is empty. Did you use chromefy.sh instead of croissant? Do you think using fydeos, samus and swtpm.tar causes it to power wash? Will try building the image again later in linux ubuntu as i have done the image using chrome os.

**Comment by MuntashirAkon** [comment]
> Did you use chromefy.sh instead of croissant?

**Chromefy** and **Croissant** are the same script (renamed for some unavoidable reason).

> Do you think using fydeos, samus and swtpm.tar causes it to power wash?

Probably. But it doesn't matter since everything is working as expected.

**Comment by MuntashirAkon** [comment]
Just test the new **install_chromium.sh** on CrOS to confirm that it's working as expected.

**Comment by b1t0y** [comment]
> Just test the new install_chromium.sh on CrOS to confirm that it's working as expected.

I have it installed it using Chrome OS and it worked! But after rebooting I did not see the disk drive in clover right away.  I have to press F3 to show.  Then booted into chrome after power wash without any problem.  I'm not sure if it is my setup in clover is the reason why it does not show right away.

**Comment by MuntashirAkon** [comment]
Closed #1
