### ISSUE TITLE
faild to start google play

### ISSUE THREAD

**Issue by HassanAhmadAli** [MuntashirAkon/Chrome-OS-Multiboot#10]

**Comment by MuntashirAkon** [comment]
This is a known issue. Google Play doesn't work now and then after updating using this method. This is a problem with the Chromefy method itself I think.

**Comment by Genxster1998** [comment]
+69 

Here too , ARC++ Container failed to start ,arc.log says some error accessing state apk-cache permission denied but it could be false positive error recorded there.
Chrome OS build r81 
BTW I am using brunch updated chrome os ,further I think there could be some assertions before starting arc which lead to such error , I am getting like this is not genuine chrome device error somewhere like in enabling debugging features at start.

**Comment by MuntashirAkon** [comment]
> I am using brunch updated chrome os

Doesn't the ChromeOS default update work in Brunch?

> ARC++ Container failed to start ,arc.log says some error accessing state apk-cache permission denied but it could be false positive error recorded there.

Could you send me the logs?

**Comment by Genxster1998** [comment]
@MuntashirAkon Yes , As brunch containerized solution replicate chrome OS very well it works with stability .I just used Root-A of same .and  doesn't works .
However there's another init exist which offers to solve android container some times in brunch not related to this scheme (hdd 2 or 3 parttion installation).Will try that flag !
Will give you arc++ log later on ,currently out of town .Further Fyde OS does work in 2 partitions with android container .

**Comment by HassanAhmadAli** [comment]
thanks❤️
