### ISSUE TITLE
to save the mount-internals.conf you gave a wrong command or an outdated one 

### ISSUE THREAD

**Issue by Zarvis12** [MuntashirAkon/Chrome-OS-Multiboot#11]
I used this in my new Rammus 86
to save it
`sudo cp /home/chronos/user/Downloads/mount-internals.conf /etc/init/`

**Comment by MuntashirAkon** [comment]
> `sudo cp /home/chronos/user/Downloads/mount-internals.conf /etc/init/`

So what does `~` point to? Run `echo ~` to see if you're unsure.

**Comment by Zarvis12** [comment]
it points to root folder
[image: Screenshot 2020-11-14 at 1.38.14 PM.png]

**Comment by Zarvis12** [comment]
It points to root folder so, I've changed the path accordingly to my downloads folder which is in `/home/chronos/user/`
![image](https://user-images.githubusercontent.com/36318260/99142901-52653a80-267f-11eb-9752-51e03cfe9866.png)

**Comment by Zarvis12** [comment]
![image](https://user-images.githubusercontent.com/36318260/99142975-ef27d800-267f-11eb-92cf-d63035641dac.png)

I didn't know that those commands can run normally. 
I've run that command through `sudo` privilages
So it points to root folder so, I've changed the path accordingly to my downloads folder which is in /home/chronos/user/

but when I run it with normally it points as you told it...
 any way it worked and my drives mount

**Comment by MuntashirAkon** [comment]
Well, since I've used `sudo` explicitly, it's expected that you run it in normal mode (as opposed to `root` mode).
