### ISSUE TITLE
Error while running chromefy.sh

### ISSUE THREAD

**Issue by neptalactone** [MuntashirAkon/Chrome-OS-Multiboot#12]
Hi, i running into this error while running the chromefy.sh that tells me i don't have enough free space, i have 100GB+ availabile free space on my drive that i do the chromefy. Here's the error message:
```

cp: cannot create directory '/home/chronos/local/boot': No space left on device
'/home/chronos/RAW/usr/lib64/dri/i965_dri.so' -> '/home/chronos/local/usr/lib64/dri/i965_dri.so'
cp: error writing '/home/chronos/local/usr/lib64/dri/i965_dri.so': No space left on device
'/home/chronos/RAW/usr/lib64/dri/swrast_dri.so' -> '/home/chronos/local/usr/lib64/dri/swrast_dri.so'
cp: error writing '/home/chronos/local/usr/lib64/dri/swrast_dri.so': No space left on device
'/home/chronos/RAW/usr/lib64/dri/kms_swrast_dri.so' -> '/home/chronos/local/usr/lib64/dri/kms_swrast_dri.so'
cp: error writing '/home/chronos/local/usr/lib64/dri/kms_swrast_dri.so': No space left on device
'/home/chronos/RAW/usr/lib64/dri/nouveau_dri.so' -> '/home/chronos/local/usr/lib64/dri/nouveau_dri.so'
cp: error writing '/home/chronos/local/usr/lib64/dri/nouveau_dri.so': No space left on device
'/home/chronos/RAW/usr/lib64/va/drivers/i965_drv_video.so' -> '/home/chronos/local/usr/lib64/va/drivers/i965_drv_video.so'
cp: error writing '/home/chronos/local/usr/lib64/va/drivers/i965_drv_video.so': No space left on device
```

Of course that is not all, i only copied a few last error on the terminal. Here's the picture.
![error1](https://user-images.githubusercontent.com/34985816/107165050-276f5600-69e4-11eb-9935-403e1d761ac1.png)

The error happen both when i include swtpm.tar or not. At first i ignored the error and proceed to boot the chromeOS. But It will always get stuck after GRUB. 

I'm using zork recovery image of chromeOS and my laptop specs are AMD Ryzen 3550H. Do you have any idea what happen and how to solve it? I've been trying the brunch method too, it will boot chromeOS, but then it will get stuck on chrome logo, but i can access it's terminal (using ctrl+alt+f2) when i get stuck. It is because my CPU not supported? I read that zork recovery support for AMD Ryzen 3XXX series. and when i use other recovery image (grunt), brunch will not boot into chromeOS and proceed to bootloop.

**Comment by MuntashirAkon** [comment]
It says no space left on device. You should probably work on that.

**Comment by neptalactone** [comment]
Yes, but what its mean? is it mean the image or my drive? but i doubt it is my drive because i still have 100 GB+ space left

**Comment by neptalactone** [comment]
> 
> 
> It says no space left on device. You should probably work on that.

Yes, but what its mean? is it mean the image or my drive? but i doubt it is my drive because i still have 100 GB+ space left

**Comment by neptalactone** [comment]
I use the latest chromium build from arnold repo (version 87) and also use  zork recovery of chromeos version 87

**Comment by MuntashirAkon** [comment]
Well, it is suggesting that your current partition doesn't have sufficient space. This error is produced by the `cp` shell command which checks for spaces before it copies.

**Comment by neptalactone** [comment]
I know that, but i think this happen because the chromium image doesn't have enough sufficient space to handle the additional files from chrome recovery images. Because from what i understand, the chromefy script both mounted the chromiumOS image and chromeOS image to the temporary directory outside the /home directory. This doesn't have directly to do with my home partition space. And i also doubt 100 GB+ space is insufficient for a chrome/chromium os. It's not like i compile the chromiumos/chromeos  myself.

**Comment by MuntashirAkon** [comment]
Yeah, this could an issue too.

**Comment by neptalactone** [comment]
So, in theory, i could extract both images onto the new folder, then make a new image from that new folder and be able to boot? It's not because my CPU not supported right?

**Comment by MuntashirAkon** [comment]
Could be. I'm not up to date with Croissant and Brunch communities as I'm now against chromefication since it actively promotes Google monopoly. Chromefy script is also not up to date as they now recommend Brunch seeing that most people want to install Chrome just to use Android apps.

**Comment by neptalactone** [comment]
Ah i see. Thanks. I think i just waiting for FreeBSD 13 stable then.

**Comment by MuntashirAkon** [comment]
Personally, I would go for Void or Artix.

**Comment by neptalactone** [comment]
> Personally, I would go for Void or Artix.

I already install arch on my laptop. My laptop has Windows, Arch linux, OpenSUSE, and Kali Linux. And i want to try other operating system on my machine. It's just a hobby of mine. So if chromiumos and/or chromeos are out of option, then i go to freeBSD next, but currently freebsd version 12.2 didn't support my Wifi-card yet, so i was waiting for ath10k driver drop to freebsd version 13.0
