### ISSUE TITLE
chrome://flags is missing

### ISSUE THREAD

**Issue by MuntashirAkon** [MuntashirAkon/Chrome-OS-Multiboot#2]
I used croissant.sh instead of chromefy.sh and fydeos6.0.img with samus73.bin recovery and swtpm.tar to have chrome:flags enabled in chrome. Coz when i use eve and caroline recovery chrome:flags on chrome is empty. Did you use chromefy.sh instead of croissant? Do you think using fydeos, samus and swtpm.tar causes it to power wash? Will try building the image again later in linux ubuntu as i have done the image using chrome os.

_Originally posted by @b1t0y in https://github.com/MuntashirAkon/Chrome-OS-Multiboot/issues/1#issuecomment-484040341_

**Comment by MuntashirAkon** [comment]
As mentioned in [this issue](https://github.com/imperador/chromefy/issues/40#issuecomment-473664806). It's something to do with TPM.

**Comment by b1t0y** [comment]
> As mentioned in this issue. It's something to do with TPM.

I only see chrome:flags with combination of eve or nocturne recovery + swtpm.tar.  Right now Im using samus recovery + swtpm.tar and no chrome:flags.  Do you know any work around on this?  I wanted to enable google assistant in samus recovery.  In eve or nocturne it works without any problem.

**Comment by MuntashirAkon** [comment]
> Do you know any work around on this?

No, I don't. Need to study further. Probably comparing the `/etc/` folders of the two recoveries may hint us something.

**Comment by MuntashirAkon** [comment]
> I wanted to enable google assistant in samus recovery.

Although off-topic: Are you using the same version of ATB/FydeOS, samus, tpm recovery? Google Play, Google Assistant may not work if you don't use the same versions.

**Comment by b1t0y** [comment]
FydeOS is based on r72, samus is 73 and swtpm has no specific version. If i use all 72 would it work? Thanks.

**Comment by MuntashirAkon** [comment]
> FydeOS is based on r72, samus is 73 and swtpm has no specific version. If i use all 72 would it work? Thanks.

I don't know.

**Comment by Crescendo-BLYAT** [comment]
@MuntashirAkon this can be fixed for good if you use **swtpm.tar**...

the bug is not actually a bug, its the OS unable to take ownership of hardware TPM chip due to some OEM's bogus implementation of TPM like Acer's only can be modified by Windows OS.

if you manage to integrate the cros_update.sh for using against **swtpm.tar**, it'll be breeze....

https://github.com/arnoldthebat/chromiumos/issues/274

**Comment by MuntashirAkon** [comment]
Thanks for the advice.
