### ISSUE TITLE
placing chrome flags using chrome os without booting to linux os

### ISSUE THREAD

**Issue by b1t0y** [MuntashirAkon/Chrome-OS-Multiboot#3]
> !! PRO TIPS !! You can also test them inside Chrome OS (will be reset upon a restart), to do that run the following commands on CrOS terminal:
> 
> sudo su
> cp /etc/chrome_dev.conf /usr/local/
> mount --bind /usr/local/chrome_dev.conf /etc/chrome_dev.conf
> exit
> Now, you can use vim editor to edit the file.
> 
> sudo vim /etc/chrome_dev.conf

What I did to put chrome flags directly on chrome os: 

1. Ctrl-alt-t for crosh terminal --> shell
2. sudo su
3. sudo mount -o remount,rw /
4. cd /etc
5. sudo vim chrome_dev.conf
6. cut and paste your chromeflags or type it
7. press shift q then w enter then q enter
8. reboot
It work for me...

**Comment by MuntashirAkon** [comment]
Thanks for the advice. With the current update, however, these steps are no longer needed since `Chrome://flags` is working fine.
