### ISSUE TITLE
"System is repairing" error on mmcblk devices

### ISSUE THREAD

**Issue by rote66** [MuntashirAkon/Chrome-OS-Multiboot#8]
I used install_chromium.sh to install the os to hdd.
Then i booted to chromeos,it boot starts with "system is repairing" only a few second then reboot,And in the process of cycling.

How to judge what the problem is.
Thanks.

**Comment by MuntashirAkon** [comment]
Was there any errors while running `install_chromium.sh`?

**Comment by rote66** [comment]
> Was there any errors while running `install_chromium.sh`?

No,just have one problem,but not report error: 
sed: -e expression 1, char 51: unknown option to `s'
Them i change the " to '.
And the script runs normally and no problem. 
Maybe this just my bash problem,but not effect install system.

**Comment by MuntashirAkon** [comment]
This usually happens when values in `/usr/sbin/write_got.sh` or `grub.cfg` are wrong.

**Comment by MuntashirAkon** [comment]
Is it by any chance NVME or mmcblk device?

**Comment by rote66** [comment]
> Is it by any chance NVME or mmcblk device?

yes,mmcblk

**Comment by MuntashirAkon** [comment]
> yes,mmcblk

I've updated the repo to support mmcblk. Try the new script.

**Comment by rote66** [comment]
> > yes,mmcblk
> 
> I've updated the repo to support mmcblk. Try the new script.

I tried,but same problem.

**Comment by MuntashirAkon** [comment]
> I tried,but same problem.

Did you get the same error while running the script?

**Comment by rote66** [comment]
> > I tried,but same problem.
> 
> Did you get the same error while running the script?

I tried it again ,redownload the script ,it works fine.Thanks.

**Comment by MuntashirAkon** [comment]
Fixed via https://github.com/MuntashirAkon/Chrome-OS-Multiboot/commit/a83e6879f72ac94217e7b2856ca25c819dd5e6ea
