### ISSUE TITLE
Is there a way to make the efi-system partition get together with windows esp partition？

### ISSUE THREAD

**Issue by mitltl** [MuntashirAkon/Chrome-OS-Multiboot#9]
More partitions make disk more mess. So I want to put efi-system to esp partition. It is possible to work?

**Comment by MuntashirAkon** [comment]
If you're not looking for A/B update, it's possible. You'll need to add a boot entry in your grub.cfg (or whatever bootloader you're using).

**Comment by MuntashirAkon** [comment]
However, the script doesn't support such method (due to overly complications). I can make efi partition optional and output a grub entry if you're looking for one.

**Comment by mitltl** [comment]
> If you're not looking for A/B update, it's possible. You'll need to add a boot entry in your grub.cfg (or whatever bootloader you're using).

I think so. The updater may not work normally.

**Comment by mitltl** [comment]
> However, the script doesn't support such method (due to overly complications). I can make efi partition optional and output a grub entry if you're looking for one.

Thx, it is unnecessary now. I have already installed your updater. Thx again, thanks for your working.
